# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_thumb',
            field=models.ImageField(default=datetime.datetime(2015, 12, 9, 15, 15, 33, 204625, tzinfo=utc), upload_to='uploads/%Y/%m/%d/', verbose_name='Thumbnail'),
            preserve_default=False,
        ),
    ]
