# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_project_project_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(max_length=225, verbose_name='Project URL'),
        ),
    ]
